catalog = [ 
  {
    "_id": "emroone",
    "title": "Sticker",
    "price": 12.50,
    "stock": 11,
    "category": "Merch",
    "image":"avst1.jpg",
    "discount": 5,
  },
  {
    "_id": "emrosix",
    "title": "Sticker",
    "price": 12.50,
    "stock": 16,
    "category": "Merch",
    "image":"avst2.jpg",
    "discount": 5,
  },
  {
    "_id": "emrothree",
    "title": "T-Shirt",
    "price": 20.00,
    "stock": 13,
    "category": "Clothing",
    "image":"avts1.jpg",
    "discount": 5,
  },
  {
    "_id": "emroeight",
    "title": "T-Shirt",
    "price": 20.00,
    "stock": 18,
    "category": "Clothing",
    "image":"avts2.jpg",
    "discount": 5,
  },
  {
    "_id": "emrotwo",
    "title": "Print",
    "price": 25.,
    "stock": 12,
    "category": "Merch",
    "image":"avpt1.jpg",
    "discount": 5,
  },
  {
    "_id": "emroseven",
    "title": "Print",
    "price": 25.,
    "stock": 17,
    "category": "Merch",
    "image":"avpt2.jpg",
    "discount": 5,
  },
  {
    "_id": "emrofour",
    "title": "Hoodie Shirt",
    "price": 30.00,
    "stock": 14,
    "category": "Clothing",
    "image":"avhd1.jpg",
    "discount": 5,
  },
  {
    "_id": "emronine",
    "title": "Hoodie Shirt",
    "price": 30.00,
    "stock": 19,
    "category": "Clothing",
    "image":"avhd2.jpg",
    "discount": 5,
  },
  {
    "_id": "emrofive",
    "title": "Original",
    "price": 250.00,
    "stock": 15,
    "category": "Artwork",
    "image":"avor1.jpg",
    "discount": 5,
  },
  {
    "_id": "emroten",
    "title": "Original",
    "price": 250.00,
    "stock": 10,
    "category": "Artwork",
    "image":"avor2.jpg",
    "discount": 5,
  }
]
